spring:
  profiles:
    active: default

---

spring:
  profiles: default

  application:
    name: user

  datasource:
    url: jdbc:mysql://localhost:3307/egov_llm_platform?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: teammate
    password: tm1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: user
          destination: backend
          contentType: application/json
        event-out:
          destination: backend
          contentType: application/json

jwt:
  secret: my-secret-jwt-key
  expirationMs: 3600000

api:
  url:
    user: http://localhost:8082

server:
  port: 8082

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

---

spring:
  profiles: docker

  application:
    name: user

  datasource:
    url: jdbc:mysql://mysql-llm:3306/egov_llm_platform?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: teammate
    password: tm1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: user
          destination: backend
          contentType: application/json
        event-out:
          destination: backend
          contentType: application/json

jwt:
  secret: my-secret-jwt-key
  expirationMs: 3600000

api:
  url:
    user: http://user:8080

server:
  port: 8080
