spring:
  profiles:
    active: default

---
spring:
  profiles: default

  application:
    name: agent

  # === MySQL (JPA: Agent 등) ===
  datasource:
    url: jdbc:mysql://18.117.111.18:3306/egov_llm_platform?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: teammate          # (권장) 루트 대신 전용 계정
    password: tm1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  # === MongoDB (ConversionLog 등) ===
  # === MongoDB (URI로 명시, 로컬은 27019 주의) ===
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27019/conversion_db?authSource=admin
      auto-index-creation: true

  # === Kafka (Cloud Stream) ===
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: agent
          destination: backend
          contentType: application/json
        event-out:
          destination: backend
          contentType: application/json

server:
  port: 8084

aws:
  region: ap-northeast-2
  s3:
    bucket: codefile-storage
  credentials:
    # 환경변수 또는 EC2 Role 권장. 미설정 시 빈 값 허용
    accessKey: 
    secretKey: 

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

---
spring:
  profiles: docker

  application:
    name: agent

  # === MySQL (컨테이너 네트워크용) ===
  datasource:
    url: jdbc:mysql://mysql-llm:3306/egov_llm_platform?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: teammate
    password: tm1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  # === MongoDB (컨테이너 네트워크용) ===
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: conversion_db
      username: admin
      password: admin123
      authentication-database: admin

  # === Kafka (컨테이너 네트워크용) ===
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: agent
          destination: backend
          contentType: application/json
        event-out:
          destination: backend
          contentType: application/json

server:
  port: 8080
