server:
  port: 8080

spring:
  application:
    name: agent
---

spring:
  profiles: default
  data:
    mongodb:
      uri: mongodb://admin:admin123@52.79.240.52:27017/conversion_db?authSource=admin
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: conversion_db
#      username: admin
#      password: admin123
#      authentication-database: admin
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: java
#<<< EDA / Topic Name
          destination: python-message
#>>> EDA / Topic Name
          contentType: application/json
        event-out:
#<<< EDA / Topic Name
          destination: java-message
#>>> EDA / Topic Name
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug


server:
  port: 8084

aws:
  region: ap-northeast-2
  s3:
    bucket: codefile-storage
  credentials:
    accessKey: 
    secretKey: 



---

spring:
  profiles: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: agent
          destination: backend
          contentType: application/json
        event-out:
          destination: backend
          contentType: application/json


